### ISSUE TITLE
precisamos de uma FK

### ISSUE THREAD

**Issue by breno-sapucaia** [TechSow/nac-humberto#2]
Gente, precisamos de uma ```FK```, tava falando com o Carlos aqui na FIAP no intervalo do SHIFT que estou fazendo, e ele tinha terminado a NAC na aula de sexta feira mesmo e mostrou para o *humberto*, ele tinha feito igual a gente,  uma entidade usuario no banco tranquilo.<br/>

só que ai o humberto disse que tava muito simples, que ele gostaria de ver um tratamento de FK  para deixar completo a nac englobando todos os tratamentos que ele fez na camada de BO,

a ideia então, mais simples que não foge do escopo do projeto da AM seria o cadastro da 
PESSOA, ou seja, o usuario não teria mais nome, apenas
```
id_usuario 
email
senha
```

e uma nova entidade pessoa com alguns dados mais pessoais do usuário
```
nome
sobrenome
idade
fk_usuario
```

**por que não colocar a fk de pessoa no usuário?**<br/>
Porque fazendo dessa forma não forçamos o cadastro da pessoa antes de ter um usuário.

o que vocês acham?

**Comment by TechSow** [comment]
"Porque fazendo dessa forma não forçamos o cadastro da pessoa antes de ter um usuário."
Nao entendi essa parte.
A gente nao deveria, no momento em que cadastramos uma pessoa, ja cadastrar tambem um usuario?
Tipo, o aluno vai se cadastrar, ai ele passa todas as informacoes de PESSOA e de USUARIO. 
Ai, quando a gente chamar a funcao de cadastrar pessoa, a gente ja cadastra o usuario tambem. 
Essa seria a forma correta de popular essas duas entidades, certo?

**Comment by breno-sapucaia** [comment]
não necessariamente, pois ai quando o aluno se cadastra como USUARIO ele passa só o e-mail e a senha, e depois que ele ta na plataforma ele preenche os dados pessoais dele, opcionalmente, igual no github, a não ser que seja uma regra de negócio o aluno ter que passar os dados pessoais dele como PESSOA e depois como USUARIO, onde posicionar essa FK, no usuario ou na pessoa, nos da a versatilidade de criar um antes do outro e visse versa

**Comment by breno-sapucaia** [comment]
além de ser uma abordagem mais tranquila e menos direta, forçar o usuário imputar os dados principais dele antes de cadastrar efetivamente um usuário e senha para acessar a plataforma
